### Create a new user
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "email": "dasdas@dffdsf.fdfd",
    "password": "das45"
}

### Find a particular user with a given ID
GET http://localhost:5000/auth/2

### Find all users with a given email
GET http://localhost:5000/auth?email=dasdas@dffdsf.fdfd

### Update a user
PATCH http://localhost:5000/auth/1
Content-Type: application/json

{
    "email": "aaaa@aaaa.com"
}

### Delete a user with a given id
DELETE http://localhost:5000/auth/1